#!/bin/bash
set -xe

# create koji devops tags/targets/etc

EL=el7

osg-koji add-tag --arches=x86_64 devops-$EL-production
osg-koji add-tag --arches=x86_64 devops-$EL-itb

osg-koji add-tag-inheritance --noconfig devops-$EL-production  osg-$EL
osg-koji add-tag-inheritance devops-$EL-itb devops-$EL-production

osg-koji add-target {kojira-fake-,}devops-$EL-production kojira-fake
osg-koji add-target {kojira-fake-,}devops-$EL-itb kojira-fake

