#!/bin/bash
set -xe

# create koji series-upcoming tags/targets/etc for osg series/elX

SERIES=3.5
EL=el7


### new tags ###

osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-build
osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-development
osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-prerelease
osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-release
osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-testing
osg-koji add-tag --arches=x86_64 osg-$SERIES-upcoming-$EL-rolling
osg-koji edit-tag --perm=release-team --lock osg-$SERIES-upcoming-$EL-release
osg-koji add-tag-inheritance --priority=0 --noconfig osg-$SERIES-upcoming-$EL-prerelease  osg-$EL

osg-koji add-tag-inheritance --priority=3  osg-$SERIES-upcoming-$EL-build         osg-$SERIES-$EL-build
osg-koji add-tag-inheritance --priority=0  osg-$SERIES-upcoming-$EL-build         osg-$SERIES-upcoming-$EL-development
osg-koji add-tag-inheritance --priority=0  osg-$SERIES-upcoming-$EL-development   osg-$SERIES-upcoming-$EL-testing
osg-koji add-tag-inheritance --priority=0  osg-$SERIES-upcoming-$EL-release       osg-$EL
osg-koji add-tag-inheritance --priority=0  osg-$SERIES-upcoming-$EL-testing       osg-$SERIES-upcoming-$EL-release
osg-koji add-tag-inheritance --priority=1  osg-$SERIES-upcoming-$EL-rolling       osg-$SERIES-upcoming-$EL-release

osg-koji add-target kojira-fake-osg-$SERIES-upcoming-$EL-development  osg-$SERIES-upcoming-$EL-development  kojira-fake
osg-koji add-target osg-$SERIES-upcoming-$EL                          osg-$SERIES-upcoming-$EL-build        osg-$SERIES-upcoming-$EL-development
osg-koji add-target kojira-fake-osg-$SERIES-upcoming-$EL-rolling      osg-$SERIES-upcoming-$EL-rolling      kojira-fake

