#!/bin/bash


tarballs_dir=${1-}

die () {
    echo "$@" 1>&2
    exit 1
}

if [[ -z $tarballs_dir ]]; then
    die "Tarballs directory not specified or null. This is /usr/local/repo/tarball-install on repo.grid.iu.edu"
fi

if [[ ! -d $tarballs_dir ]]; then
    die "$tarballs_dir is not a directory"
fi

set -o errexit
set -o verbose

cd $tarballs_dir


mkdir 3.1
for dir in 3.1.*; do
    mv $dir 3.1/$dir
done

for symlink in *-latest*.tar.gz; do
    rm -f $symlink
    ln -s 3.1/$symlink $symlink
done


