#!/bin/bash

tarballs_dir=${1:-/usr/local/repo/tarball-install}

die () {
    echo "$@" 1>&2
    exit 1
}

. $(dirname $0)/assert.sh || die "Could not load $(dirname $0)/assert.sh"

if [[ ! -d $tarballs_dir ]]; then
    die "$tarballs_dir is not a directory"
fi

cd $tarballs_dir

dvers=(el5 el6)
arches=(i386 x86_64)
versions31=(3.1.16 3.1.17 3.1.18 3.1.19 3.1.20 3.1.21 3.1.22)
metapkgs=(osg-wn-client osg-client)

if [[ ! -d 3.1 ]]; then
    die "3.1 doesn't exist, can't continue"
fi

pushd 3.1 >/dev/null
for dver in ${dvers[*]}; do
    for arch in ${arches[*]}; do
        for metapkg in ${metapkgs[*]}; do
            assert "[[ -L $metapkg-latest.$dver.$arch.tar.gz ]]"
            assert "[[ `readlink -f $metapkg-latest.$dver.$arch.tar.gz` == *${versions31[${#versions31[*]} - 1]}* ]]"
        done
    done
done
popd >/dev/null

if [[ ${ASSERT_FAIL:-0} -eq 0 ]]; then
    echo "No problems."
else
    echo "There were some problems, see above."
    exit 1
fi

