#!/bin/bash

tarballs_dir=${1-}

die () {
    echo "$@" 1>&2
    exit 1
}

. $(dirname $0)/assert.sh || die "Could not load $(dirname $0)/assert.sh"

if [[ -z $tarballs_dir ]]; then
    die "Tarballs directory not specified or null. This is /usr/local/repo/tarball-install on repo.grid.iu.edu"
fi

if [[ ! -d $tarballs_dir ]]; then
    die "$tarballs_dir is not a directory"
fi

cd $tarballs_dir

dvers=(el5 el6)
arches=(i386 x86_64)
versions31=(3.1.16 3.1.17 3.1.18 3.1.19 3.1.20 3.1.21 3.1.22)
versions32=(3.2.0 3.2.1)
metapkgs=(osg-wn-client osg-client)

if [[ ! -d 3.1 ]]; then
    die "3.1 doesn't exist, can't continue"
fi

for dver in ${dvers[*]}; do
    for arch in ${arches[*]}; do
        for metapkg in ${metapkgs[*]}; do
            pushd 3.1 >/dev/null
            assert "[[ -L $metapkg-latest.$dver.$arch.tar.gz ]]"
            assert "[[ `readlink -f $metapkg-latest.$dver.$arch.tar.gz` == *${versions31[${#versions31[*]} - 1]}* ]]"
            popd >/dev/null
            if [[ ! -d 3.2 ]]; then
                echo "skipping 3.2 tests"
            else
                pushd 3.2 >/dev/null
                assert "[[ -L $metapkg-latest.$dver.$arch.tar.gz ]]"
                assert "[[ `readlink -f $metapkg-latest.$dver.$arch.tar.gz` == *${versions32[${#versions32[*]} - 1]}* ]]"
                popd >/dev/null
            fi
        done
    done
done


