#!/bin/bash

yum_dir="3.0"
yum_dir_old="3.0.old"
yum_dir_new="3.0.new"

# Check for expected environment
if [ -d $yum_dir_old ]; then
    die "$yum_dir_old already exists, something's broken"
fi

if [ -d $yum_dir_new ]; then
    die "$yum_dir_new already exists, something's broken"
fi

(
    set -o errexit

    pushd $yum_dir > /dev/null
    
    echo "Setting up '$yum_dir_new'..."
    for arch in el5 el6; do
        symlink_dir="$yum_dir_new/$arch"
        mkdir -p $symlink_dir
        for release in contrib development testing release; do
            ln -s "../../osg/3.1/$arch/$release" "$arch/osg-$release"
            if [ $release != "contrib" ]; then
                ln -s "../../osg/upcoming/$arch/$release" "osg-upcoming-$release"                
            fi
        done
    done

    popd > /dev/null
        
    echo "Moving dirs into their proper locations..."
    mv $yum_dir $yum_dir_old
    mv $yum_dir_new $yum_dir
)
ret=$?
if [ $ret -eq 0 ]; then
    echo "Migration successful."
    echo "Verify contents of '$yum_dir', then go ahead and remove '$yum_dir_old'."
else
    echo "Migration failed somewhere."
    echo "ROLLBACK! ROLLBACK!"
fi
