#!/bin/bash

new_yum_dir=${1:-/usr/local/repo/osg}

die () {
    echo "$@" 1>&2
    exit 1
}

# Check for expected environment
if [ -d $new_yum_dir ]; then
    die "$new_yum_dir already exists, something's broken"
fi

(
    set -o errexit

    pushd `dirname $new_yum_dir` > /dev/null

    # Make OSG NEXT directory structure
    echo "Creating new directory structure..."
    for version in 3.1 3.2 upcoming; do
        for arch in el5 el6; do
            for release in contrib development testing release; do
                if [ $version == "upcoming" ] && [ $release == contrib ]; then
                    continue
                else
                    mkdir -p osg/$version/$arch/$release
                fi
            done
        done
    done

    popd > /dev/null
)
ret=$?
if [ $ret -eq 0 ]; then
    echo "Migration successful."
    echo "Verify contents of '$new_yum_dir'."
else
    echo "Migration failed somewhere."
    echo "You can safely remove '$new_yum_dir'."
fi
