#!/bin/bash
set -e

cd "$(dirname "$0")"

./pull-from-koji
./get-trunk-dirs > trunk-dirs
./mk-newtags
./whatsmissing > missing.list

# only run these when ready to make changes to koji
#./create-tags
#./tag-builds

