#!/bin/bash
set -e

cd "$(dirname "$0")"

./pull-from-koji
./get-trunk-dirs > package-list
./mk-newtags
./whatsmissing > missing.txt

# only run these when ready to make changes to koji
#./create-tags
#./tag-builds

